//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitorEntryPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeservice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employeeservice()
        {
            this.latelogouts = new HashSet<latelogout>();
        }
    
        public int id { get; set; }
        public Nullable<int> employeeid { get; set; }
        public short serviceid { get; set; }
        public Nullable<System.DateTime> intime { get; set; }
        public Nullable<System.DateTime> outtime { get; set; }
        public Nullable<long> tempbadgeno { get; set; }
        public Nullable<int> remarkid { get; set; }
        public System.DateTime created_on { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<long> modified_by { get; set; }
    
        public virtual comment comment { get; set; }
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<latelogout> latelogouts { get; set; }
    }
}
