//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitorEntryPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VisitorEntities : DbContext
    {
        public VisitorEntities()
            : base("name=VisitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<employeeservice> employeeservices { get; set; }
        public virtual DbSet<latelogout> latelogouts { get; set; }
        public virtual DbSet<lookup> lookups { get; set; }
        public virtual DbSet<lookupgroup> lookupgroups { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userlogin> userlogins { get; set; }
        public virtual DbSet<visitorservice> visitorservices { get; set; }
    }
}
